server:
  port: ${SERVER_PORT:8000}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:19092}
    schema-registry: ${SCHEMA_REGISTRY:http://localhost:8085}

logging:
  file:
    name: "log"
management:
  endpoints:
    web:
      exposure:
        include: "*"