server:
  port: ${SERVER_PORT:9000}

spring:
  enviroment:
    id: ${VEICULO_ID:1}
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:19092}
    schema-registry: ${SCHEMA_REGISTRY:http://localhost:8085}

logging:
  file:
    name: "log"
management:
  endpoints:
    web:
      exposure:
        include: "*"